Repository OSMChina/BusFensi, pull requests merged in 2025-03, with the labels that each got.

#9 build(actions): deploy to branch instead of pages
  .github/workflows/vite-build-deploy.yml
Labels: size/S

#10 build(action): add CNAME, rename branch from gh-pages to pages
  .github/workflows/vite-build-deploy.yml
Labels: size/XS

#11 debug: remove cname
  .github/workflows/vite-build-deploy.yml
Labels: size/XS

#12 merge(dev->main): bus stop edit functions fin
  src/components/modal/CreateFeatureTagConfirm.tsx
  src/components/modal/CreateFeatureTagConfirmHook.tsx
  src/components/modal/SimpleConfirm.tsx
  src/components/modal/SimpleConfirmHook.tsx
  src/components/osm/CreateFeatureTags.tsx
  src/components/osm/create/CreateFeatureMemberItem.tsx
  src/components/osm/create/MemberListWithDel.tsx
  src/components/osm/create/RelationsMemberEdit.tsx
  src/store/osmmeta/slice/bus/action.ts
  src/store/osmmeta/slice/meta/helper.ts
  src/store/osmmeta/slice/meta/initialState.ts
  src/type/osm/presets.d.ts
  src/utils/osm/presets/bus.ts
  src/views/map/components/RightCLickMenu.tsx
  src/views/map/components/collection/base/item.tsx
  src/views/map/mode/ptedit/index.tsx
  src/views/map/stateMachine/ptEdit/index.ts
  src/views/map/stateMachine/ptEdit/slice/BusTabComponent.ts
  src/views/property/components/Tags.tsx
  src/views/property/views/RelationProperty.tsx
  tsconfig.app.tsbuildinfo
Labels: size/XL

#13 merge: dev -> main, route edit tab
  docs/TODO.md
  src/components/dnd/DragList.tsx
  src/components/modal/CreateFeatureTagConfirmHook.tsx
  src/components/osm/member/RoleInput.tsx
  src/components/osm/memberDrag/MemberListSel.tsx
  src/components/pixi/Point.tsx
  src/store/osmmeta/selector.ts
  src/store/osmmeta/slice/bus/action.ts
  src/store/osmmeta/slice/bus/initialState.ts
  src/store/osmmeta/slice/bus/selector.ts
  src/store/osmmeta/slice/featureState/action.ts
  src/store/osmmeta/slice/meta/helper.ts
  src/type/osm/presets.d.ts
  src/type/stateMachine/ptEdit/index.ts
  src/utils/osm/featureTypeEnum.ts
  src/utils/osm/nodeType.ts
  src/utils/osm/presets/bus.ts
  src/utils/osm/relationType.ts
  src/views/map/components/collection/route/index.tsx
  src/views/map/components/collection/route/route.tsx
  src/views/map/components/collection/route/routemaster.tsx
  src/views/map/components/routeEdit/BusRouteMemberListDelDel.tsx
  src/views/map/mode/ptedit/index.tsx
  src/views/map/mode/ptedit/tab/bus.tsx
  src/views/map/mode/ptedit/tab/route.tsx
  src/views/map/stateMachine/ptEdit/busStop.ts
  src/views/map/stateMachine/ptEdit/routeAddPath.ts
  src/views/map/stateMachine/ptEdit/routeAddStop.ts
  src/views/map/stateMachine/ptEdit/slice/BusTabComponent.ts
  src/views/map/stateMachine/slice/components/BatchSelectStateMachine.ts
  src/views/property/components/DisplayWayConnectivity.tsx
  src/views/property/components/FeatureRelaion.tsx
  src/views/property/components/MemberListSelWithDelDown.tsx
  src/views/property/views/RelationProperty.tsx
Labels: size/XXL

#14 feat & optims: added the tabs feature property/views comps, optimised…
  src/components/pixi/Line.tsx
  src/components/pixi/Point.tsx
  src/utils/osm/filterV2.ts
  src/views/map/mode/ptedit/index.tsx
  src/views/outline/base/tab.tsx
  src/views/property/views/NodeProperty.tsx
  src/views/property/views/RelationProperty.tsx
  src/views/property/views/WayProperty.tsx
Labels: size/L
